# placeholder yml config file
Compose:
  - Key : uniqueid1
    Path : /tmp/orkester-working/mainapp
    Repo : https://github.com/shukriadams/orkester-container1-config.git
    ComposePath : /docker-compose-main.yml
    Enabled : true
    Trigger : tag
    BackupMask : "*/5 * * * * *"
    BackupCommand : echo "backup worked"
